services:
  couchdb-peer2:
    container_name: couchdb-peer2.lab.example.com
    image: couchdb:3.3
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    networks:
      - fabric

  peer2.lab.example.com:
    container_name: peer2.lab.example.com
    image: hyperledger/fabric-peer:${FABRIC_VERSION}
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${FABRIC_NETWORK}
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb-peer2:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      - CORE_PEER_ID=${PEER2_HOST}
      - CORE_PEER_ADDRESS=${PEER2_HOST}:${PEER_PORT}
      - CORE_PEER_LISTENADDRESS=0.0.0.0:${PEER_PORT}
      - CORE_PEER_CHAINCODEADDRESS=${PEER2_HOST}:${CHAINCODE_PORT}
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:${CHAINCODE_PORT}
      - CORE_PEER_GOSSIP_BOOTSTRAP=${LOCAL_BOOTSTRAP_PEER}
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=${PEER2_HOST}:${PEER_PORT}
      - CORE_PEER_LOCALMSPID=${LAB_MSP_ID}
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9444
      - CORE_METRICS_PROVIDER=prometheus
    working_dir: /root
    command: peer node start
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../.generated/fabric-samples/config:/etc/hyperledger/peercfg
      - ../organizations/peerOrganizations/lab.example.com/peers/peer2.lab.example.com/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/lab.example.com/peers/peer2.lab.example.com/tls:/etc/hyperledger/fabric/tls
      - ../data/peer2:/var/hyperledger/production
    ports:
      - "${PEER_PORT}:${PEER_PORT}"
    depends_on:
      - couchdb-peer2
    networks:
      - fabric

networks:
  fabric:
    name: ${FABRIC_NETWORK}

